### ISSUE TITLE
RedisStore - TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by himasimplisafe** [arthurfiorette/axios-cache-interceptor#165]
Using Redis store to get, set,remove. And i see below exception

`err: TypeError: Cannot read property 'data' of undefined
    at t.adapter (/node_modules/axios-cache-interceptor/cjs/index.js:1:3074)`

I do not see cjs/index.js in `[axios-cache-interceptor](https://github.com/arthurfiorette/axios-cache-interceptor)` repo

**Comment by arthurfiorette** [comment]
`cjs/index.js` is the minified file compatible with commonsjs. Depending in your version, you can see it on `jsdelivr`, or even inside your node modules.

There's no default Redis store. Can you paste here your code?

**Comment by himasimplisafe** [comment]
I am just using redisStore mentioned here https://axios-cache-interceptor.js.org/#/pages/storages?id=creating-your-own-storage

**Comment by arthurfiorette** [comment]
Well, i'm not sure if that example is working... :p

Can you enable [source maps](https://nodejs.medium.com/source-maps-in-node-js-482872b56116#d608) & [development mode](https://axios-cache-interceptor.js.org/#/pages/development-mode) and send the output here again?

**Comment by himasimplisafe** [comment]
With source maps option enabled, i see below output

`TypeError: Cannot read property 'data' of undefined
    at t.adapter (node_modules/axios-cache-interceptor/cjs/index.js:1:3074)
    at dispatchRequest (node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)`

**Comment by himasimplisafe** [comment]
Here is my code:

`import {
  setupCache,
  buildStorage,
  CacheAxiosResponse,
  AxiosCacheInstance,
  CacheProperties,
} from 'axios-cache-interceptor';

const redisStorage = buildStorage({
  find: async (key) => {
    const getVal = await redis.get(`axios-cache:${key}`);
    return getVal;
  },
  set: async (key, value) => {
    await redis.set(`axios-cache:${key}`, JSON.stringify(value));
  },
  remove: async (key) => {
    await redis.expire(`axios-cache:${key}`, 60);
  },
});

let httpRequest: AxiosCacheInstance = null;

export const requestInitializer = (): void => {
  try {
    httpRequest = setupCache(request.axiosInstance, {
      ttl: 60,
      storage: redisStorage,
    });
  } catch (err) {
    log.error({
      message: `Failed to initialize! `,
      err,
    });
  }
};`

**Comment by himasimplisafe** [comment]
With umd development mode enabled, here is the output

`node_modules/axios-cache-interceptor/umd/dev.js:1
!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.AxiosCacheInterceptor=t():e.AxiosCacheInterceptor=t()}("undefined"!=typeof self?self:this,(function(){return(()=>{"use strict";var e={d:(t,a)=>{for(var r in a)e.o(a,r)&&!e.o(t,r)&&Object.defineProperty(t,r,{enumerable:!0,get:a[r]})},o:(e,t)=>Object.prototype.hasOwnProperty.call(e,t),r:e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})}},t={};e.r(t),e.d(t,{Header:()=>s,buildKeyGenerator:()=>E,buildMemoryStorage:()=>I,buildStorage:()=>S,buildWebStorage:()=>T,canStale:()=>y,createCacheResponse:()=>g,createValidateStatus:()=>d,defaultHeaderInterpreter:()=>i,defaultKeyGenerator:()=>j,defaultRequestInterceptor:()=>h,defaultResponseInterceptor:()=>m,isExpired:()=>x,isMethodIn:()=>u,isStorage:()=>w,setupCache:()=>R,testCachePredicate:()=>l,updateCache:()=>p,updateStaleRequest:()=>f});const a=Symbol("cache-parser");function r(e){return("string"==typeof e||"number"==typeof e)&&(e=Number(e))>=0&&e<1/0}function n(e){return!0===e||"number"==typeof e||"string"==typeof e&&"false"!==e}const o=Number;const s=Object.freeze({IfModifiedSince:"if-modified-since",LastModified:"last-modified",IfNoneMatch:"if-none-match",CacheControl:"cache-control",ETag:"etag",Expires:"expires",Age:"age",XAxiosCacheEtag:"x-axios-cache-etag",XAxiosCacheLastModified:"x-axios-cache-last-modified",XAxiosCacheStaleIfError:"x-axios-cache-stale-if-error"}),i=e=>{if(!e)return"not enough headers";const t=e[s.CacheControl];if(t){const{noCache:i,noStore:c,mustRevalidate:d,maxAge:u,immutable:f}=function(e){const t=Object.defineProperty({},a,{enumerable:!1,value:1});if(!e||"string"!=typeof e)return t;const s=function(e){const t={},a=e.toLowerCase().replace(/\s+/g,"").split(",");for(const e in a){var r;const n=a[e].split("=",2);t[n[0]]=null==(r=n[1])||r}return t}(e),i=s["max-age"],c=s["max-stale"],d=s["min-fresh"],u=s["s-maxage"],f=s["stale-if-error"],g=s["stale-while-revalidate"];return n(s.immutable)&&(t.immutable=!0),r(i)&&(t.maxAge=o(i)),r(c)&&(t.maxStale=o(c)),r(d)&&(t.minFresh=o(d)),n(s["must-revalidate"])&&(t.mustRevalidate=!0),n(s["must-understand"])&&(t.mustUnderstand=!0),n(s["no-cache"])&&(t.noCache=!0),n(s["no-store"])&&(t.noStore=!0),n(s["no-transform"])&&(t.noTransform=!0),n(s["only-if-cached"])&&(t.onlyIfCached=!0),n(s.private)&&(t.private=!0),n(s["proxy-revalidate"])&&(t.proxyRevalidate=!0),n(s.public)&&(t.public=!0),r(u)&&(t.sMaxAge=o(u)),r(f)&&(t.staleIfError=o(f)),r(g)&&(t.staleWhileRevalidate=o(g)),t}(String(t));if(i||c)return"dont cache";if(f)return 31536e6;if(d)return 0;if(u){const t=e[s.Age];return t?1e3*(u-Number(t)):1e3*u}}const i=e[s.Expires];if(i){const e=Date.parse(String(i))-Date.now();return e>=0?e:"dont cache"}return"not enough headers"},c=Symbol();function d(e){return e?t=>e(t)||304===t:e=>e>=200&&e<300||304===e}function u(e="get",t=[]){e=e.toLowerCase();for(const a of t)if(a.toLowerCase()===e)return!0;return!1}function f(e,t){t.headers||(t.headers={});const{etag:a,modifiedSince:r}=t.cache;if(a){const r=!0===a?e.data?.headers[s.ETag]:a;r&&(t.headers[s.IfNoneMatch]=r)}r&&(t.headers[s.IfModifiedSince]=!0===r?e.data.headers[s.LastModified]||new Date(e.createdAt).toUTCString():r.toUTCString())}function g(e,t){return 304===e.status&&t?(e.cached=!0,e.data=t.data,e.status=t.status,e.statusText=t.statusText,e.headers={...t.headers,...e.headers},t):{data:e.data,status:e.status,statusText:e.statusText,headers:e.headers}}function h(e){const t=async t=>{if(!1===t.cache)return e.debug?.({msg:"Ignoring cache because config.cache is false",data:t}),t;if(t.cache={...e.defaults.cache,...t.cache},!u(t.method,t.cache.methods))return e.debug?.({msg:`Ignored because method (${t.method}) is not in cache.methods (${t.cache.methods})`}),t;const a=t.id=e.generateKey(t);let r,n=await e.storage.get(a);e:if("empty"===n.state||"stale"===n.state){if(e.waiting[a]){n=await e.storage.get(a),e.debug?.({id:a,msg:"Waiting list had an deferred for this key, waiting for it to finish"});break e}return e.waiting[a]=function(){let e,t;const a=new Promise(((a,r)=>{e=a,t=r}));return a.resolve=e,a.reject=t,a[c]=1,a}(),e.waiting[a]?.catch((()=>{})),await e.storage.set(a,{state:"loading",previous:n.state,data:n.data,createdAt:n.createdAt}),"stale"===n.state&&(f(n,t),e.debug?.({id:a,msg:"Updated stale request"})),t.validateStatus=d(t.validateStatus),e.debug?.({id:a,msg:"Sending request, waiting for response"}),t}if("loading"===n.state){const n=e.waiting[a];if(!n)return await e.storage.remove(a),t;e.debug?.({id:a,msg:"Detected concurrent request, waiting for it to finish"});try{r=await n}catch(r){return e.debug?.({id:a,msg:"Deferred rejected, requesting again",data:r}),t}}else r=n.data;return t.adapter=()=>Promise.resolve({config:t,data:r.data,headers:r.headers,status:r.status,statusText:r.statusText,cached:!0,id:a}),e.debug?.({id:a,msg:"Returning cached response"}),t};return{onFulfilled:t,apply:()=>e.interceptors.request.use(t)}}async function l(e,t){if("function"==typeof t)return t(e);const{statusCheck:a,responseMatch:r,containsHeaders:n}=t;if(a&&!await a(e.status)||r&&!await r(e))return!1;if(n)for(const t in n){const a=n[t];if(a&&!await a(e.headers[t.toLowerCase()]??e.headers[t]))return!1}return!0}async function p(e,t,a){for(const r in a){const n=a[r];if("delete"===n){await e.remove(r);continue}const o=await e.get(r);if("loading"===o.state)continue;const s=await n(o,t);"delete"!==s?"ignore"!==s&&await e.set(r,s):await e.remove(r)}}function m(e){const t=async t=>{await e.storage.remove(t),e.waiting[t]?.reject(null),delete e.waiting[t]},a=async a=>{var r;if(a.id=(r=a.config).id??(r.id=e.generateKey(a.config)),a.cached??(a.cached=!1),a.cached)return e.debug?.({id:a.id,msg:"Returned cached response"}),a;if(!a.config.cache)return e.debug?.({id:a.id,msg:"Response with config.cache === false",data:a}),{...a,cached:!1};const n=a.config.cache,o=await e.storage.get(a.id);if("stale"===o.state||"empty"===o.state||"cached"===o.state)return e.debug?.({id:a.id,msg:"Response not cached but storage is not loading",data:{cache:o,response:a}}),a;if(!o.data&&!await l(a,n.cachePredicate))return await t(a.id),e.debug?.({id:a.id,msg:"Cache predicate rejected this response"}),a;for(const e in s)e.startsWith("XAxiosCache")&&delete a.headers[e];n.etag&&!0!==n.etag&&(a.headers[s.XAxiosCacheEtag]=n.etag),n.modifiedSince&&(a.headers[s.XAxiosCacheLastModified]=!0===n.modifiedSince?"use-cache-timestamp":n.modifiedSince.toUTCString());let i=n.ttl||-1;if(n?.interpretHeader){const r=e.headerInterpreter(a.headers);if("dont cache"===r)return await t(a.id),e.debug?.({id:a.id,msg:"Cache header interpreted as 'dont cache'",data:{cache:o,response:a,expirationTime:r}}),a;i="not enough headers"===r?i:r}const c=g(a,o.data);"function"==typeof i&&(i=await i(a)),n.staleIfError&&(a.headers[s.XAxiosCacheStaleIfError]=String(i)),e.debug?.({id:a.id,msg:"Useful response configuration found",data:{cacheConfig:n,ttl:i,cacheResponse:c}}),n?.update&&await p(e.storage,a,n.update);const d={state:"cached",ttl:i,createdAt:Date.now(),data:c},u=e.waiting[a.id];return u&&(u.resolve(d.data),delete e.waiting[a.id],e.debug?.({id:a.id,msg:"Found waiting deferred(s) and resolved them"})),await e.storage.set(a.id,d),e.debug?.({id:a.id,msg:"Response cached",data:{cache:d,response:a}}),a},r=async a=>{const r=a.config;if(!r||!1===r.cache||!r.id)throw e.debug?.({msg:"Web request returned an error but cache handling is not enabled",data:{error:a,config:r}}),a;const n=await e.storage.get(r.id),o=r.cache;if("loading"!==n.state||"stale"!==n.previous)throw await t(r.id),e.debug?.({msg:"Caught an error in the request interceptor",data:{error:a,config:r}}),a;if(o?.staleIfError){const t="function"==typeof o.staleIfError?await o.staleIfError(a.response,n,a):o.staleIfError;if(e.debug?.({msg:"Found cache if stale config for rejected response",data:{error:a,config:r,staleIfError:t}}),!0===t||"number"==typeof t&&n.createdAt+t>Date.now())return e.waiting[r.id]?.resolve(n.data),delete e.waiting[r.id],await e.storage.set(r.id,{state:"stale",createdAt:Date.now(),data:n.data}),e.debug?.({msg:"staleIfError resolved this response with cached data",data:{error:a,config:r,cache:n}}),{cached:!0,config:r,id:r.id,data:n.data.data,headers:n.data.headers,status:n.data.status,statusText:n.data.statusText}}throw e.debug?.({msg:"Received an unknown error that could not be handled",data:{error:a,config:r}}),a};return{onFulfilled:a,onRejected:r,apply:()=>e.interceptors.response.use(a,r)}}const b=Symbol(),w=e=>!!e&&!!e[b];function y(e){const t=e.data.headers;return s.ETag in t||s.LastModified in t||s.XAxiosCacheEtag in t||s.XAxiosCacheStaleIfError in t||s.XAxiosCacheLastModified in t}function x(e){return e.createdAt+e.ttl<=Date.now()}function S({set:e,find:t,remove:a}){return{[b]:1,set:e,remove:a,get:async r=>{const n=await t(r);if(!n)return{state:"empty"};if("cached"!==n.state||!x(n))return n;if(y(n)){const t={state:"stale",createdAt:n.createdAt,data:n.data};return await e(r,t),t}return await a(r),{state:"empty"}}}}function I(){const e=S({find:t=>e.data[t],set:(t,a)=>{e.data[t]=a},remove:t=>{delete e.data[t]}});return e.data=Object.create(null),e}function v(e){const t=typeof e;if(e&&"object"==t&&!(e instanceof Date||e instanceof RegExp)){const t=Array.isArray(e)?[]:{};for(const a in e)t[a]=v(e[a]);return`${e.constructor}${JSON.stringify(t,Object.keys(e).sort())}`}return`${t}${String(e)}`}function C(e){e=v(e);let t=5381,a=0;for(;a<e.length;)t=33*t^e.charCodeAt(a++);return t}const A=/^\/|\/$/g;function E(e){return t=>{if(t.id)return t.id;const a=e(t);return"string"==typeof a||"number"==typeof a?`${a}`:`${C(a)}`}}const j=E((({baseURL:e="",url:t="",method:a="get",params:r,data:n})=>(e&&(e=e.replace(A,"")),t&&(t=t.replace(A,"")),a&&(a=a.toLowerCase()),{url:e+(e&&t?"/":"")+t,params:r,method:a,data:n})));function R(e,t={}){const a=e;if(a.storage=t.storage||I(),!w(a.storage))throw new Error("Use buildStorage() function");return a.generateKey=t.generateKey||j,a.waiting=t.waiting||{},a.headerInterpreter=t.headerInterpreter||i,a.requestInterceptor=t.requestInterceptor||h(a),a.responseInterceptor=t.responseInterceptor||m(a),a.debug=t.debug,a.defaults.cache={ttl:t.ttl??3e5,interpretHeader:t.interpretHeader??!1,methods:t.methods||["get"],cachePredicate:t.cachePredicate||{statusCheck:e=>e>=200&&e<400},etag:t.etag??!1,modifiedSince:t.modifiedSince??!1,staleIfError:t.staleIfError??!1,update:t.update||{}},a.requestInterceptor.apply(),a.responseInterceptor.apply(),a}function T(e,t=""){return S({find:a=>{const r=e.getItem(t+a);return r?JSON.parse(r):void 0},remove:a=>{e.removeItem(t+a)},set:(a,r)=>{const n=()=>e.setItem(t+a,JSON.stringify(r));try{return n()}catch(r){const o=Object.entries(e).filter((([a])=>a.startsWith(t)&&e.getItem(a))).map((([e,t])=>[e,JSON.parse(t)]));for(const[t,a]of o)"cached"===a.state&&x(a)&&!y(a)&&e.removeItem(t);try{return n()}catch(t){const a=o.sort((([,e],[,t])=>(e.createdAt||0)-(t.createdAt||0)));for(const[t]of a){e.removeItem(t);try{return n()}catch(e){}}}e.removeItem(t+a)}}})}return console.error("You are using a development build. Make sure to use the correct build in production"),console.error("https://axios-cache-interceptor.js.org/#/pages/installing"),t})()}));


SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.require.extensions.<computed> [as .js] (node_modules/ts-node/src/index.ts:851:44)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:893:16)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (src/lib/falcon.ts:13:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module.m._compile (node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.require.extensions.<computed> [as .ts] (node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:893:16)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (src/lib/notifySms.ts:24:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module.m._compile (node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.require.extensions.<computed> [as .ts] (node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:893:16)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (src/test/integration/notifications.test.ts:43:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module.m._compile (node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.require.extensions.<computed> [as .ts] (node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:893:16)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.implementationOfRequireOrImportForUnstableEsm [as requireOrImport] (node_modules/mocha/lib/nodejs/esm-utils.js:116:12)
    at Object.exports.loadFilesAsync (node_modules/mocha/lib/nodejs/esm-utils.js:103:34)
    at singleRun (node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (node_modules/mocha/lib/cli/run.js:374:5)`

**Comment by arthurfiorette** [comment]
Well, this isn't helpful... 
But, can you make some `console.log`s to check the output returned by the redis api calls?

Like, they are always returning a "complete" object? The `buildStorage `checks if the find() method returned `undefined`, but it don't check if it returned a valid object (e.g: has `state:'cached'`) with `cache.data` being undefined. (e.g: `{ state: 'cached', data: undefined, ... }`).

It may also be your redis instance that saved (from a previous test/bug/whatever) that saved data as `undefined` and it's returning like so.

**Comment by himasimplisafe** [comment]
redis api calls do not return complete object, they just return a value for the key you set right

**Comment by arthurfiorette** [comment]
Of course. Tried to follow some coed that you posted above and seems that this is the failing line:

https://github.com/arthurfiorette/axios-cache-interceptor/blob/f140b0267c7219086ede19c097a5ef64b11eb556/src/interceptors/request.ts#L153

Are you sure that your storage isn't messing with any stored cache?

Because that line can only throw an error if `cache.data` (returned from your storage) is undefined.

https://github.com/arthurfiorette/axios-cache-interceptor/blob/f140b0267c7219086ede19c097a5ef64b11eb556/src/interceptors/request.ts#L145

**Comment by himasimplisafe** [comment]
If you see here for the first time request made `{ state: 'loading', previous: 'empty', data: undefined, createdAt: undefined }` state is `loading`, in this case `cachedResponse = await deferred;`

**Comment by arthurfiorette** [comment]
Are you sure that the request was `'loading'`? Because if it is, the deferred is resolved with the method `createCacheResponse`. And it never returns undefined.

https://github.com/arthurfiorette/axios-cache-interceptor/blob/f140b0267c7219086ede19c097a5ef64b11eb556/src/interceptors/util.ts#L72-L100

https://github.com/arthurfiorette/axios-cache-interceptor/blob/f140b0267c7219086ede19c097a5ef64b11eb556/src/interceptors/response.ts#L147

https://github.com/arthurfiorette/axios-cache-interceptor/blob/f140b0267c7219086ede19c097a5ef64b11eb556/src/interceptors/response.ts#L170-L175

https://github.com/arthurfiorette/axios-cache-interceptor/blob/f140b0267c7219086ede19c097a5ef64b11eb556/src/interceptors/response.ts#L181

A more plausible solution is that the request had `state: 'cached'`, so it got in this line:

https://github.com/arthurfiorette/axios-cache-interceptor/blob/f140b0267c7219086ede19c097a5ef64b11eb556/src/interceptors/request.ts#L144-L146

In which your redis storage retured a `cached` state with `data` as `undefined`.

Anyways, to speed up the process, can you create a unit test or a example repo that i can reproduce the issue myself? Because even if the redis storage is returning `state: cached` with `data: undefined`, I don't know why.

**Comment by arthurfiorette** [comment]
Also, you can enable debug mode by importing `import { setupCache } from 'axios-cache-interceptor/cjs/dev;` and using `debug: console.log` as a option together with `ttl` and `storage`.

**Comment by himasimplisafe** [comment]
When i have `debug: console.log`, I am seeing below
`SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.require.extensions.<computed> [as .js] node_modules/ts-node/src/index.ts:851:44)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)`

**Comment by arthurfiorette** [comment]
Well, can you provide a [minimum reproduction repository](http://minimum-reproduction.wtf/) ?

**Comment by arthurfiorette** [comment]
> When i have `debug: console.log`, I am seeing below `SyntaxError: Unexpected token '.' at wrapSafe (internal/modules/cjs/loader.js:1070:16) at Module._compile (internal/modules/cjs/loader.js:1120:27) at Module._extensions..js (internal/modules/cjs/loader.js:1176:10) at Object.require.extensions.<computed> [as .js] node_modules/ts-node/src/index.ts:851:44) at Module.load (internal/modules/cjs/loader.js:1000:32) at Function.Module._load (internal/modules/cjs/loader.js:899:14) at Module.require (internal/modules/cjs/loader.js:1042:19) at require (internal/modules/cjs/helpers.js:77:18)`

Wow, this error is happening because `./cjs/dev` (or `umd` / `esm`) isn't defined in the "exports" inside `package.json`.

Figured it out when trying to run a example on runkit and with Node 17 it prints out a better error information.

I'll fix it in the next patch version...

A tempfix for this problem is to just add these keys in `exports`.
```json
  "./cjs/dev": "./cjs/dev.js",
  "./esm/dev": "./esm/dev.js",
  "./umd/dev": "./umd/dev.js"
```

Add it in `node_modules/axios-cache-interceptor-package.json` and it'll work.

![image](https://user-images.githubusercontent.com/47537704/157655674-779d37b9-2592-4628-b9e9-9b0c59fbefaf.png)

**Comment by arthurfiorette** [comment]
Please, provide a [minimum reproduction repository](http://minimum-reproduction.wtf/).

We are this far and I don't know what version you are using of this package, what node version or even what axios version.

**Comment by arthurfiorette** [comment]
But that will only enables debugging mode. If with the memory storage everything works fine, The problem has something with your redis instance (and / or) storage.

If I had access to the code, i'd have started looking for inconsistences in the redis storage response, (like, for every find() method call print the object that will be returned). Because it seems that, for some reason, your storage is returning a object with `{ state: 'cached' , data: undefined, ... }`.

> Are you sure that the request was `'loading'`? Because if it is, the deferred is resolved with the method `createCacheResponse`. And it never returns undefined.
> 
> https://github.com/arthurfiorette/axios-cache-interceptor/blob/f140b0267c7219086ede19c097a5ef64b11eb556/src/interceptors/util.ts#L72-L100
> 
> https://github.com/arthurfiorette/axios-cache-interceptor/blob/f140b0267c7219086ede19c097a5ef64b11eb556/src/interceptors/response.ts#L147
> 
> https://github.com/arthurfiorette/axios-cache-interceptor/blob/f140b0267c7219086ede19c097a5ef64b11eb556/src/interceptors/response.ts#L170-L175
> 
> https://github.com/arthurfiorette/axios-cache-interceptor/blob/f140b0267c7219086ede19c097a5ef64b11eb556/src/interceptors/response.ts#L181
> 
> A more plausible solution is that the request had `state: 'cached'`, so it got in this line:
> 
> https://github.com/arthurfiorette/axios-cache-interceptor/blob/f140b0267c7219086ede19c097a5ef64b11eb556/src/interceptors/request.ts#L144-L146
> 
> In which your redis storage retured a `cached` state with `data` as `undefined`.

**Comment by himasimplisafe** [comment]
you mentioned every find() method call print the object that will be returned, below is where the find method definition is?
https://github.com/arthurfiorette/axios-cache-interceptor/blob/98f9c5a9f41d27610b45040c395e843d679e2aae/src/storage/memory.ts#L29
I have put bunch of logs in axios-cache-interceptor's request.ts, util.ts, none of the logs are printed, but i do see redis storage methods are printing keys for me. Also, in my test, i am just calling

  `
  it('cache', async () => {
    await redis.set(
      'axios-cache:807109091',
      JSON.stringify({
        state: 'cached',
        ttl: 1,
        createdAt: 1646856634457,
        data: {
          data: { some data },
          status: 200,
          statusText: null,
          headers: { 'content-type': 'application/json' },
        },
      })
    );
    requestInitializer();
    //make http request here
  });`

**Comment by arthurfiorette** [comment]
> you mentioned every find() method call print the object that will be returned, below is where the find method definition is?

Oh, i meant in your implementation of the `find()` method, because the above is the implementation for the memory storage one.

> I have put bunch of logs in axios-cache-interceptor's request.ts, util.ts, none of the logs are printed

That's because all files in `src/` are the source files (and in typescript). As NodeJS only understands javascript files, i have to transpile my typescript files into javascript. That's why there's a `cjs/index.js` minified file.

Use this code as your redis storage. Then you can see what the find() method returned to the interceptor before it crashed.

```js
const redisStorage = buildStorage({
  find: async (key) => {
    const cache = await redis.get(`axios-cache:${key}`);
    console.log('Called find():', { key, cache });
    return cache;
  },
  set: async (key, value) => {
    console.log('Called set():', { key, value });
    await redis.set(`axios-cache:${key}`, JSON.stringify(value));
  },
  remove: async (key) => {
    console.log('Called remove():', { key });
    await redis.expire(`axios-cache:${key}`, 60);
  }
});
```

**Comment by himasimplisafe** [comment]
Here is the output running my tests

`Called find(): { key: '807109091', cache: null }
Called set(): {
  key: '807109091',
  value: {
    state: 'loading',
    previous: 'empty',
    data: undefined,
    createdAt: undefined
  }
}
Called find(): { key: '807109091', cache: '{"state":"loading","previous":"empty"}' }
Called set(): {
  key: '807109091',
  value: {
    state: 'cached',
    ttl: 1,
    createdAt: 1646934218923,
    data: {
      data: [Object],
      status: 200,
      statusText: null,
      headers: [Object]
    }
  }
}
in test, responseCached: {
  ttl: 1,
  interpretHeader: false,
  methods: [ 'get' ],
  cachePredicate: { statusCheck: [Function: statusCheck] },
  etag: false,
  modifiedSince: false,
  staleIfError: false,
  update: {}
}
Called find(): {
  key: '807109091',
  cache: '{"state":"cached","ttl":1,"createdAt":1646934218923,"data":{"data":{}},"status":200,"statusText":null,"headers":{"content-type":"application/json"}}}'
}`

**Comment by arthurfiorette** [comment]
I guess that i can't help you more without a [minimum reproduction repository](http://minimum-reproduction.wtf/).

**Comment by himasimplisafe** [comment]
> I guess that i can't help you more without a [minimum reproduction repository](http://minimum-reproduction.wtf/).

I do not have anything else to give you other than the code i have given already, hence closed the issue

**Comment by arthurfiorette** [comment]
Well, with a minimum repository i could try to debug on my own and resolve it for you..

I'm going to let this issue open for when I have time to build a sample from the ground and try to reproduce it.

**Comment by himasimplisafe** [comment]
Interestingly, i am not seeing `[TypeError: Cannot read property 'data' of undefined](https://github.com/arthurfiorette/axios-cache-interceptor/issues/165#)` all the time, i wonder i need some await for buildStorage or seupCache. If you have working code with setupCache with redisStorage, can you put that code here?

**Comment by arthurfiorette** [comment]
@himasimplisafe Can you test if #169 is the fix? Maybe we just forgot to use `JSON.parse` :)

**Comment by arthurfiorette** [comment]
Well, I'm don't know much about different redis instructions, there's any major difference?

> Also, how we can generate a custom key for custom storage, so that in tests i can look for that key

```js
// You can force custom keys:
// https://axios-cache-interceptor.js.org/#/pages/per-request-configuration?id=id
const response = await axios.get('url', {
  id: 'custom key'
});

// Or get what id was used:
// https://axios-cache-interceptor.js.org/#/pages/response-object?id=id
const usedIdForThisRequest = response.id;
```

Went to read the documentation and it isn't good. I guess that i'll have to rewrite a lot of things today :)

**Comment by cipriandraghici93** [comment]
@arthurfiorette  I figured the same issue but using localStorage. What I observed is having multiple gets to the same endpoint with a custom id and invalidating the request by id before executing the next to get request, then this error occurred. Probably because the code expects to have the request already cached. But I expect that if the request is not cached then do the original request to DB. 
I also observed that when this error appears all the following requests will fail and checking the network I observed that no request is made.

**Comment by arthurfiorette** [comment]
Hmm, can you create a simple reproducible example?

**Comment by cipriandraghici93** [comment]
> 

https://codesandbox.io/s/busy-northcutt-3erj7v

Press multiple times "Refetch" button

![image](https://user-images.githubusercontent.com/11082863/159944027-6866883c-b188-40ca-8e29-1292dcc5d6f9.png)

**Comment by arthurfiorette** [comment]
Alright, I'm short in time but I'll work on it as soon as I can.

**Comment by arthurfiorette** [comment]
Hey @cipriandraghici93. It was a pretty strange bug. But thanks to you I could find and fix it.

Long story short, together along the cache data, a waiting promise (`axios.waiting[key]`) is also created in a two way sync. When you deleted manually the cache with `cache.update` or even by `axios.storage.remove(key)`, that waiting promise remained.

And the code broke in a pretty complicated way. _(And the nodejs event loop didn't help to find why and solve it)_ 🥲.

But anyways, I fixed it and will publish a patch version asap.

@himasimplisafe, sorry for not resolving this earlier.

**Comment by himasimplisafe** [comment]
@arthurfiorette no worries, thanks for fixing it. Waiting for version with the fix.

**Comment by cipriandraghici93** [comment]
@arthurfiorette Thanks a lot. I appreciate.

**Comment by arthurfiorette** [comment]
@cipriandraghici93 and @himasimplisafe, I've just published v0.10.2.

It's safe to close this issue for now?

**Comment by himasimplisafe** [comment]
maybe @cipriandraghici93 can try new version and see if issue is resolved

**Comment by cipriandraghici93** [comment]
@arthurfiorette Hey! I tested and is not reproducible anymore. I think you can close the issue. Thanks again for the fast fix!

**Comment by nullbytesoftware** [comment]
Hey im having a similar issue to this. On both cases of page first load and if i manually clear local storage the request is never fired. I have dev enabled and the last message i see is `msg: 'Detected concurrent request, waiting for it to finish'` but it never finishes waiting. 

And in the local storage this value exists `{"state":"loading","previous":"empty"}`

**Comment by arthurfiorette** [comment]
Hey @nullbytesoftware, can you open a dedicated issue to it? Also by adding a reproductible example?
