### ISSUE TITLE
bug: something is wrong :(

### ISSUE THREAD

**Issue by james-hu** [arthurfiorette/axios-cache-interceptor#244]
### Describe the bug

I am trying to use it in AWS Lambda. The tool chain I am using is serverless and serverless-webpack plugin.
Webpack complains about "Can't import ... from non EcmaScript module" in Node 14 environment:

```
[2022-05-18T10:10:53.414Z] ERROR in ./node_modules/axios-cache-interceptor/dist/index.mjs 1:1278-1288

[2022-05-18T10:10:53.414Z] Can't import the named export 'deferred' from non EcmaScript module (only default export is available)

[2022-05-18T10:10:53.414Z]  @ ./api.ts

[2022-05-18T10:10:53.414Z]  @ ./handler.ts

[2022-05-18T10:10:53.414Z] 

[2022-05-18T10:10:53.414Z] ERROR in ./node_modules/axios-cache-interceptor/dist/index.mjs 1:6483-6489

[2022-05-18T10:10:53.414Z] Can't import the named export 'hash' from non EcmaScript module (only default export is available)

[2022-05-18T10:10:53.414Z]  @ ./api.ts

[2022-05-18T10:10:53.414Z]  @ ./handler.ts

[2022-05-18T10:10:53.414Z] 

[2022-05-18T10:10:53.414Z] ERROR in ./node_modules/axios-cache-interceptor/dist/index.mjs 1:485-492

[2022-05-18T10:10:53.414Z] Can't import the named export 'parse' from non EcmaScript module (only default export is available)

[2022-05-18T10:10:53.414Z]  @ ./api.ts

[2022-05-18T10:10:53.414Z]  @ ./handler.ts

[2022-05-18T10:10:53.414Z]  

[2022-05-18T10:10:53.414Z]  Error ---------------------------------------------------

[2022-05-18T10:10:53.414Z]  

[2022-05-18T10:10:53.414Z]   Error: Webpack compilation error, see stats above

[2022-05-18T10:10:53.414Z]       at /home/ec2-user/workspace/services_feature_cache-term-info/statement/stmt-results/node_modules/serverless-webpack/lib/compile.js:37:15

[2022-05-18T10:10:53.414Z]       at arrayEach (/home/ec2-user/workspace/services_feature_cache-term-info/statement/stmt-results/node_modules/serverless-webpack/node_modules/lodash/lodash.js:530:11)

[2022-05-18T10:10:53.414Z]       at Function.forEach (/home/ec2-user/workspace/services_feature_cache-term-info/statement/stmt-results/node_modules/serverless-webpack/node_modules/lodash/lodash.js:9410:14)

[2022-05-18T10:10:53.414Z]       at /home/ec2-user/workspace/services_feature_cache-term-info/statement/stmt-results/node_modules/serverless-webpack/lib/compile.js:34:7

[2022-05-18T10:10:53.414Z]       at tryCatcher (/home/ec2-user/workspace/services_feature_cache-term-info/statement/stmt-results/node_modules/bluebird/js/release/util.js:16:23)
```

BTW, in tsconfig.json, "target" and "module" decide the compatibility level of your npm package. If you specify ESNext, that means your package can only be guaranteed to work in the environment that supports all features of ESNext. I usually set that to ES2017 so that my package can work in Node 10+.

**Comment by james-hu** [comment]
Found a workaround: 
```
config.module.rules.push({
  test: /\.mjs$/,
  include: /node_modules/,
  type: "javascript/auto",
});
```

**Comment by james-hu** [comment]
It was caused by the extension .mjs, not the compilation target.
However I still believe setting ESNext as the target is an issue.

**Comment by james-hu** [comment]
You are so quick @arthurfiorette ! Thanks for the explanation. I like the documentation. This is the first time I try to use this package, it seems to be working in our environment. So far the experience is quite good!

**Comment by arthurfiorette** [comment]
Thanks, this means a lot!
