### ISSUE TITLE
Bug: URLSearchParams serialize to empty object causing to produce same cache key for different query parameters.

### ISSUE THREAD

**Issue by VayKekaz** [arthurfiorette/axios-cache-interceptor#750]
### What happened?

`URLSearchParams` instances serialize to empty object:
```javascript
params = new URLSearchParams({ hello: 'world' }); // URLSearchParams { 'hello' => 'world' }
JSON.stringify(params); // '{}'
```

Below jest code tests this properly:

```typescript
describe('cache test', () => {
    let Axios: AxiosCacheInstance;
    const testEndpoint = 'http://localhost:8000';

    beforeAll(() => {
        Axios = setupCache(axios.create(), { ttl: 99999, interpretHeader: false, debug: console.log });
    });

    test('test URLSearchParams serialize to correct cache id', async () => {
        const paramsA = new URLSearchParams({ hello: 'world' });
        const promiseA = Axios.get(
            testEndpoint,
            { params: paramsA },
        );

        const paramsB = new URLSearchParams({ hello: 'mom' });
        const promiseB = Axios.get(
            testEndpoint,
            { params: paramsB },
        );

        const [resA, resB] = await Promise.all([promiseA, promiseB]);

        console.log('Response A:', resA.data);
        console.log('Response B:', resB.data);

        expect(resA.cached).toBe(false);
        expect(resB.cached).toBe(false); // FAILS! returns cached `resA`
    });
});
```

### axios-cache-interceptor version

1.3.2

### Node / Browser Version

20.5.1

### Axios Version

1.6.0

### What storage is being used

Memory Storage

### Relevant debugging log output

```js
console.error
    You are using a development build. Make sure to use the correct build in production
    https://axios-cache-interceptor.js.org/guide/getting-started
    
    

      1 | import axios from 'axios';
    > 2 | import { AxiosCacheInstance, setupCache } from 'axios-cache-interceptor/dev';
        | ^
      3 |
      4 |
      5 | describe('cache test', () => {

      at ../node_modules/axios-cache-interceptor/dev/webpack:/axios-cache-interceptor/src/index.ts:20:19
      at Object.<anonymous> (../node_modules/axios-cache-interceptor/dev/index.cjs:1:12787)
      at Object.<anonymous> (cache_.test.ts:2:1)

  console.log
    {
      id: '-2098784157',
      msg: 'Sending request, waiting for response',
      data: { overrideCache: false, state: 'empty' }
    }

      at t (../node_modules/axios-cache-interceptor/dev/webpack:/axios-cache-interceptor/src/interceptors/request.ts:116:33)
          at async Promise.all (index 0)

  console.log
    {
      id: '-2098784157',
      msg: 'Waiting list had an deferred for this key, waiting for it to finish'
    }

      at t (../node_modules/axios-cache-interceptor/dev/webpack:/axios-cache-interceptor/src/interceptors/request.ts:119:13)
          at async Promise.all (index 1)

  console.log
    {
      id: '-2098784157',
      msg: 'Detected concurrent request, waiting for it to finish'
    }

      at t (../node_modules/axios-cache-interceptor/dev/webpack:/axios-cache-interceptor/src/interceptors/request.ts:158:17)
          at async Promise.all (index 1)

  console.log
    {
      id: '-2098784157',
      msg: 'Useful response configuration found',
      data: {
        cacheConfig: {
          update: {},
          ttl: 99999,
          methods: [Array],
          cachePredicate: [Object],
          etag: true,
          modifiedSince: false,
          interpretHeader: false,
          cacheTakeover: true,
          staleIfError: true,
          override: false,
          hydrate: undefined
        },
        cacheResponse: {
          data: 'Hello: world',
          status: 200,
          statusText: 'OK',
          headers: [Object [AxiosHeaders]]
        }
      }
    }

      at newCache (../node_modules/axios-cache-interceptor/dev/webpack:/axios-cache-interceptor/src/interceptors/response.ts:158:15)
          at async Promise.all (index 0)

  console.log
    {
      id: '-2098784157',
      msg: 'Found waiting deferred(s) and resolved them'
    }

      at debug (../node_modules/axios-cache-interceptor/dev/webpack:/axios-cache-interceptor/src/interceptors/response.ts:180:19)
          at async Promise.all (index 0)

  console.log
    { id: '-2098784157', msg: 'Returning cached response' }

      at request (../node_modules/axios-cache-interceptor/dev/webpack:/axios-cache-interceptor/src/interceptors/request.ts:188:41)
          at async Promise.all (index 1)

  console.log
    {
      id: '-2098784157',
      msg: 'Response cached',
      data: {
        cache: {
          state: 'cached',
          ttl: 99999,
          staleTtl: undefined,
          createdAt: 1702566507592,
          data: [Object]
        },
        response: {
          status: 200,
          statusText: 'OK',
          headers: [Object [AxiosHeaders]],
          config: [Object],
          request: [ClientRequest],
          data: 'Hello: world',
          id: '-2098784157',
          cached: false
        }
      }
    }

      at isAxiosError (../node_modules/axios-cache-interceptor/dev/webpack:/axios-cache-interceptor/src/interceptors/response.ts:192:20)
          at async Promise.all (index 0)

  console.log
    { id: '-2098784157', msg: 'Returned cached response' }

      at i (../node_modules/axios-cache-interceptor/dev/webpack:/axios-cache-interceptor/src/interceptors/response.ts:55:26)
          at async Promise.all (index 1)

  console.log
    Response A: Hello: world

      at Object.<anonymous> (cache_.test.ts:30:17)

  console.log
    Response B: Hello: world

      at Object.<anonymous> (cache_.test.ts:31:17)


Error: expect(received).toBe(expected) // Object.is equality

Expected: false
Received: true
```

**Comment by arthurfiorette** [comment]
Hey @VayKekaz can you test with the latest release? v1.3.3

**Comment by VayKekaz** [comment]
@arthurfiorette thank you. it works.
