### ISSUE TITLE
Bug: Runtime Type Error in Cache-Parser Where Header Token Contains no ,

### ISSUE THREAD

**Issue by nagilson** [arthurfiorette/axios-cache-interceptor#832]
### What happened?

This code: https://github.com/arthurfiorette/tinylibs/blob/main/packages/cache-parser/src/util.ts#L18 , which this library seems to depend on, has a bug.

(I was very relieved to see you manage both libraries, so thank you for the work you do :). )

My very quick glance is the problem is the code seems to rely on the fact that , is in the header of the string that is passed to it. I dont think that assumption can always hold true, so sometimes the token ends up being null or a type other than string, so when .split is called on it, there becomes an uncaught runtime error.

I don't know much more of the context of the code here and there might be some other reason, but that is my suspicion.
Example is https://github.com/dotnet/vscode-dotnet-runtime/issues/1734.
I don't have a repro, this info is garnered from customers.
 
It is causing some issues for us over in VS Code land and it is one of our highest causes of failure, causing roughly .01% of customers to fail, with a high report rate on mac os sonoma silicon m1. 

### axios-cache-interceptor version

^1.0.1

### Node / Browser Version

16

### Axios Version

^1.3.4

### What storage is being used

Memory Storage

### Relevant debugging log output

```js
Failed: n[r].split is not a function. Aborting. Stack: TypeError: n[r].split is not a function
    at /usr/local/google/home/USER/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/javascript/esm|c:\Users\USER\vscode-dotnet-runtime\vscode-dotnet-runtime-library\node_modules\cache-parser\dist\index.mjs:1:425
    at parse (/usr/local/google/home/USER/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/javascript/esm|c:\Users\USER\vscode-dotnet-runtime\vscode-dotnet-runtime-library\node_modules\cache-parser\dist\index.mjs:1:327)
    at Function.headerInterpreter (/usr/local/google/home/USER/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/javascript/dynamic|c:\Users\USER\vscode-dotnet-runtime\vscode-dotnet-runtime-library\node_modules\axios-cache-interceptor\dist\index.cjs:2:1324)
    at n (/usr/local/google/home/USER/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/javascript/dynamic|c:\Users\USER\vscode-dotnet-runtime\vscode-dotnet-runtime-library\node_modules\axios-cache-interceptor\dist\index.cjs:2:5445)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Pt.request (/usr/local/google/home/USER/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/javascript/dynamic|c:\Users\USER\vscode-dotnet-runtime\vscode-dotnet-runtime-library\node_modules\axios\dist\node\axios.cjs:3872:7)
    at Pt.request (/usr/local/google/home/USER/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.5/javascript/dynamic|c:\Users\USER\vscode-dotnet-runtime\vscode-dotnet-runtime-library\node_modules\axios\dist\node\axios.cjs:3877:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by nagilson** [comment]
cc @baronfel

**Comment by arthurfiorette** [comment]
Hey @nagilson, can you setup a small reproducible example or paste here a `Cache-Control` header exemple value that throws the above error?

**Comment by nagilson** [comment]
Thank you so much for your _very_ fast reply.

May you help me gather that information for you? The header seems to be generated from Axios-Cache-Interceptor, so I'm not sure where it's generated. Is there something we could type in the developer console to access that information? 

The web request this is for is one for: https://dot.net/v1/dotnet-install.sh
with these options: https://github.com/nagilson/vscode-dotnet-runtime/blob/a77568a7b983d3565bbb571d31ec550442c953b5/vscode-dotnet-runtime-library/src/Utils/WebRequestWorker.ts#L168.

It does not always happen, in fact I have not been able to get it to happen.

**Comment by arthurfiorette** [comment]
Source:

```ts
const tokens = headerStr.toLowerCase().replace(/\s+/g, '').split(',');

for (const token of tokens) {
  const split = token.split('=', 2) as [string, string];
  headers[split[0]] = split[1] ?? true;
}
```

Transpiled:

```js
var a = {},
  r = e.toLowerCase().replace(/\s+/g, '').split(',');

for (var t in r) {
  var s,
    n = r[t].split('=', 2);
  a[n[0]] = null == (s = n[1]) || s;
}
```

`r` is the result of `e.toLowerCase().replace(/\s+/g, '').split(',')` which shouldn't be something else than an array, then it gets iterated in a `for (var t in r)` loop. 

Normally, `r[t]` cannot be undefined:

![image](https://github.com/arthurfiorette/axios-cache-interceptor/assets/47537704/df5eba5a-8b13-4803-bec5-5579cf4b16a5)

Am I missing something or this seems to be a bug in the js runtime?

**Comment by nagilson** [comment]
@arthurfiorette The more I am looking at the code, I am not seeing what value would cause this to happen yet either. One sec...

**Comment by arthurfiorette** [comment]
Maybe `String.prototype.split` was modified by another library?
